name: Secure Swarm Deployment

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'EU|US Cluster'
        default: 'EU'

env:
  ECR_PATH: ${{ secrets.ECR_FULL_PATH }}
  BUILD_TIMESTAMP: 2025-06-24T15:57:44Z
  SWARM_CA: /etc/docker/tls/ca.pem

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: |
        /usr/bin/docker build -t $ECR_PATH/app:$BUILD_TIMESTAMP \
          --build-arg BUILD_DATE="$BUILD_TIMESTAMP" \
          /github/workspace

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    steps:
    - run: |
        ssh -i /root/.ssh/swarm_prod_key \
          -o StrictHostKeyChecking=accept-new \
          swarm-admin@${{ secrets.SWARM_MANAGER }} \
          "docker service update \
          --image $ECR_PATH/app:$BUILD_TIMESTAMP \
          --health-cmd 'curl --cacert $SWARM_CA https://localhost/health' \
          --health-retries 3 \
          flask_prod"


