name: Secure Swarm Deployment

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'EU|US Cluster'
        default: 'EU'

env:
  ECR_PATH: ${{ secrets.ECR_FULL_PATH }}   # e.g., 123456789012.dkr.ecr.ap-south-1.amazonaws.com/flask-app
  BUILD_TIMESTAMP: ${{ github.run_id }}-${{ github.run_number }}
  SWARM_CA: /etc/docker/tls/ca.pem

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        echo "Tag: $ECR_PATH:$BUILD_TIMESTAMP"
        docker build -t $ECR_PATH:$BUILD_TIMESTAMP \
          --build-arg BUILD_DATE="$BUILD_TIMESTAMP" \
          .

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    steps:
    - name: Deploy to Docker Swarm
      run: |
        ssh -i /root/.ssh/swarm_prod_key \
          -o StrictHostKeyChecking=accept-new \
          swarm-admin@${{ secrets.SWARM_MANAGER }} \
          "docker service update \
          --image $ECR_PATH:$BUILD_TIMESTAMP \
          --health-cmd 'curl --cacert $SWARM_CA https://localhost/health' \
          --health-retries 3 \
          flask_prod"
