name: Simple Docker Deployment

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Deploy target (e.g., prod or staging)'
        default: 'prod'

env:
  ECR_PATH: ${{ secrets.ECR_FULL_PATH }}
  BUILD_TIMESTAMP: ${{ github.run_id }}-${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        echo "Building image: $ECR_PATH:$BUILD_TIMESTAMP"
        docker build -t $ECR_PATH:$BUILD_TIMESTAMP \
          --build-arg BUILD_DATE="$BUILD_TIMESTAMP" .

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Write SSH Private Key
        run: |
          echo "${{ secrets.SSH_KEY }}" > server.pem
          chmod 600 server.pem

      - name: Deploy Docker Container
        run: |
          ssh -i server.pem \
            -o StrictHostKeyChecking=accept-new \
            ec2-user@${{ secrets.DEPLOY_HOST }} \
            "
            docker pull $ECR_PATH:$BUILD_TIMESTAMP &&
            docker stop flask_prod || true &&
            docker rm flask_prod || true &&
            docker run -d --name flask_prod -p 80:5000 $ECR_PATH:$BUILD_TIMESTAMP
            "

